# -*- coding: utf-8 -*-
"""fizzbuzzpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LApZxe3V95-kBL8sLEvN1iSinG_eG3Gi

FizzBuzz
"""

for i in range(1, 101):
  # FizzBuzz
  if i%5==0 and i%3==0:
    print("FizzBuzz")
    
  #Fizz
  elif i%3==0:
    print("Fizz")
   
  #Buzz
  elif i%5==0:
    print("Buzz")
  
  # None of the above
  else: 
    print(i)

count = 0

for i in range(1, 101):
  # FizzBuzz
  if i%5==0 and i%3==0:
    print  ("FizzBuzz")
    count += 1

  #Fizz
  elif i%3==0:
    print("Fizz")
    count += 2

  #Buzz
  elif i%5==0:
    print("Buzz")
    count += 3

  # None of the above
  else: 
    print(i)

print(count)

